name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  buildtagprefix:  # id of input
    description: 'The solution being built (Dashboard.Server or Dashboard.Web)'
    required: true
    default: 'Dashboard.Server'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'